version: '3.8'

services:
  app:
    build: .
    container_name: admin-one-vue-tailwind
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173" # Cambia el puerto local al 5174
    command: ["npm", "run", "dev"]
